#!/bin/sh
cd /home/pi/www

git remote update
LOCAL=$(git rev-parse @)
REMOTE=$(git rev-parse @{u})

if [ $LOCAL != $REMOTE ]; then
	git reset --hard
	git pull https://github.com/SummerCrossedTinyRick/thorberry.git
	reboot
fi
