#!/bin/bash

kill -9 $(ps aux | grep -E "wpa_supplicant.conf$" | awk '{ print $2 }')

ip link set wlan0 up
wpa_supplicant -B -i wlan0 -D n180211,wext -c /etc/wpa_supplicant/wpa_supplicant.conf
dhclient wlan0
