#!/bin/bash

conf_file="/home/pi/www/wpa_supplicant.conf"

# create wpa_supplicant.conf file
cat /etc/wpa_supplicant/wpa_supplicant.conf > "$conf_file"
echo "$2" | wpa_passphrase "$1" >> "$conf_file"
# exec
wpa_supplicant -B -D wext -i wlan0 -c "$conf_file"
# get ip
dhclient wlan0
