#!/bin/bash

conf_file="/etc/wpa_supplicant/wpa_supplicant.conf"
iface_file="/etc/network/interfaces"

# create wpa_supplicant.conf file
cat /etc/wpa_supplicant/wpa_supplicant.conf.bak > "$conf_file"
echo "$2" | wpa_passphrase "$1" >> "$conf_file"
# exec
/sbin/wpa_supplicant -s -B -P /run/wpa_supplicant.wlan0.pid -i wlan0 -D n180211,wext -c "$conf_file"
# set static ip
cat /etc/network/interfaces.bak > "$iface_file"
# echo "iface wlan0 inet static" >> "$iface_file"
# echo -e "\taddress $3" >> "$iface_file"
# echo -e "\tnetmask $4" >> "$iface_file"
# echo -e "\tgateway $5" >> "$iface_file"

# get ip
dhclient wlan0
